/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Projects;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean IsTheCorrectValue(ArrayList<Integer> array, int index, Integer value){
        if(array == null){
            return false;
        }
        if(index < 0 || index >= array.size()){
            return false;
        }
        if(array.get(index) == value) {
            return true;
        }
        return false;
    }
}
