/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Projects;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;


class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void testNull(){
        assertFalse(App.IsTheCorrectValue(null, 1, 1));
    }

    @Test
    public void testEmptyArray(){
        ArrayList<Integer> array = new ArrayList<>();
        assertFalse(App.IsTheCorrectValue(array, -1, -1));
    }

    @Test
    public void testNotFound(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(9, 11, 23, 17, 123));
        assertFalse(App.IsTheCorrectValue(array, 3, 4));
    }

    @Test
    public void testFound(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(9, 11, 23, 17, 93, 121));
        assertTrue(App.IsTheCorrectValue(array, 3, 17));
    }
}
